CREATE TABLE IF NOT EXISTS posts
(id SERIAL PRIMARY KEY,
body VARCHAR(255) NOT NULL,
created_at TIME DEFAULT CURRENT_TIME(2),
created_on DATE DEFAULT CURRENT_DATE);

CREATE TABLE IF NOT EXISTS users
(id SERIAL PRIMARY KEY,
user_name VARCHAR(255),
password_digest VARCHAR(255),
email VARCHAR (255),
created_on DATE DEFAULT CURRENT_DATE);

CREATE TABLE IF NOT EXISTS topics
(id SERIAL PRIMARY KEY,
writing TEXT,
author VARCHAR(255)
created_on DATE DEFAULT CURRENT_DATE);

CREATE TABLE IF NOT EXISTS boards
(id SERIAL PRIMARY KEY,
title VARCHAR(255),
topics_count INTEGER,
created_on DATE DEFAULT CURRENT_DATE,
author VARCHAR(255));